server:
  port: 8001
spring:
  application:
    name: BBMALL-PLAT
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql:///bbmall-plat?useSSL=false&useUnicode=true&characterEncoding=utf8
     username: root
password: root
