server:
  port: 1314
spring:
  application:
    name: BBMALL-ZUUL-GATEWAY
zuul:
  ignored-services: "*" #用*来通配符，忽略从1314端口通过服务名来调用
  prefix: "/services" #这是所有路径的前缀
  routes:
    plat:
      path: /plat/**
      service-id: bbmall-plat
    product:
      path: /product/**
      service-id: bbmall-product